services:
  postgres:
    container_name: postgres-sql-getup
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: getup_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5435:5435
    networks:
      - spring-project
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-getup
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


volumes:
  postgres:
    driver: local

networks:
  spring-project:
    driver: bridge
